# Set the build language to Python
language: python

os:
  - linux
#  - osx
# Windows is not supported yet.
#  - windows

dist:
  - xenial

matrix:
  include:
    - os: osx
      language: generic
      env:
        - CPP=/usr/local/opt/llvm/bin/clang CPPFLAGS='-I/usr/local/opt/llvm/include -fopenmp'
	#        - LDFLAGS="-L/usr/local/opt/llvm/lib"



# Disable sudo to speed up the build
sudo: false


# Set the python versions
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install llvm; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ln -s /usr/local/opt/llvm/bin/clang /usr/local/bin/clang-omp; fi
  
install:
  - pip install -r requirements.txt
  - python setup.py install
  - pip install coverage

# Run the unit test
script:
  - nosetests -v --with-coverage --cover-tests --cover-package=tests
