# Set the build language to Python
language: python

os:
  - linux
#  - osx
# Windows is not supported yet.
#  - windows

dist:
  - xenial

matrix:
    include:
        - os: osx
          language: generic
          env: PYTHON=3.4.4
        - os: osx
          language: generic
          env: PYTHON=3.5.1

# Disable sudo to speed up the build
sudo: false


# Set the python versions
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  
install:
  - pip install -r requirements.txt
  - python setup.py install
  - pip install coverage

# Run the unit test
script:
  - nosetests -v --with-coverage --cover-tests --cover-package=tests
